export enum FieldType {
  TEXT = "TEXT",
  EMAIL = "EMAIL",
  NUMBER = "NUMBER",
  SELECT = "SELECT",
  RADIO = "RADIO",
  CHECKBOX = "CHECKBOX",
  TEXTAREA = "TEXTAREA",
  ZIP_CODE = "ZIP_CODE",
}

export enum FieldErrorType {
  REQUIRED = "REQUIRED",
  INVALID_EMAIL = "INVALID_EMAIL",
  INVALID_NUMBER = "INVALID_NUMBER",
  MAX_LENGTH_EXCEEDED = "MAX_LENGTH_EXCEEDED",
  INVALID_ZIP_CODE = "INVALID_ZIP_CODE",
}

export enum PUBLISHED_STATUS {
  DRAFT = "DRAFT",
  PUBLISHED = "PUBLISHED",
  ARCHIVED = "ARCHIVED",
}
